### ISSUE TITLE
Nginx Configuration

### ISSUE THREAD

**Issue by caduhigueras** [AmpersandHQ/magento2-log-correlation-id#18]
Hi, 

Could you provide an example of the nginx configuration to add the correlation ID in the access.log?

I have tried with the following, but it didn't work:

`# Add custom header 'X-Log-Correlation-Id'
	add_header X-Log-Correlation-Id amp_correlation_id;

	# Define the log format
	log_format examplelogformat '$time_local  $request $http_amp_correlation_id'
	#log_format examplelogformat '$time_local $request $http_amp_correlation_id'

	access_log /var/log/nginx/access.log examplelogformat;`

Thanks!

**Comment by convenient** [comment]
Hey @caduhigueras 

I don't actually have much experience with nginx, this link looks like it may be worth a shot ?
https://stackoverflow.com/questions/4272686/nginx-is-it-possible-to-capture-response-headers-in-access-log-when-using-nginx

Seems that user is also trying to add an identifier to every requests as a correlation ID.

**Comment by caduhigueras** [comment]
Great,

Will give it a try and share here if it works

Thank you

**Comment by caduhigueras** [comment]
Hi @convenient 

It seems I have managed to make it work.

Here is what I did: 

In my Magento nginx config file I have added: 

```
map $http_x_request_id $uuid {
  default   "${request_id}";
  ~*        "${http_x_request_id}";
}


...

server {

    listen 443 ssl http2;
    server_name example.com;

    access_log /var/log/nginx/m2.one-access.log m2custom;
    error_log /var/log/nginx/m2.one-error.log;
    
    ...

    proxy_set_header X-Request-ID $uuid;
    add_header X-Request-ID $uuid;

   ...

   #varnish settings
   location / {
        proxy_pass http://127.0.0.1:6081;
       
        ....

        proxy_set_header X-Request-ID $uuid;

```

Then in my /etc/nginx/nginx.conf file:


```
http {
    ...

    log_format m2custom '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent  "$http_referer" "$http_user_agent" $uuid $request_time';

   ...

```

Finally, in the module's di.xml file at app/etc/ampersand_magento2_log_correlation/di.xml:

```xml

<!-- The only dependency of the above cache decorator -->
    <type name="Ampersand\LogCorrelationId\Service\CorrelationIdentifier">
        <arguments>
            <!-- This will be the key output in log context and new relic custom parameter -->
            <argument name="identifierKey" xsi:type="string">amp_correlation_id</argument>
            <!-- configure this if you want to use an incoming log correlation id from a request header -->
            <argument name="headerInput" xsi:type="string">x-request-id</argument><!-- added x-request-id on this line -->
        </arguments>
    </type>

```

Thanks for the help!

**Comment by convenient** [comment]
Interesting! So you're using an upstream identifier and not the cid generated by Magento?

**Comment by caduhigueras** [comment]
Yes, I couldn't manage to add the id generated by Magento in the access.log, So I've searched first how to add the request unique id form nginx on the access logs and then I have added the configuration on your di.xml for this id to be used.

I am not an expert on nginx, not sure this is the most appropriate way of doing it. But it is working like charm on my tests so far.

Your module will help me a lot

Thanks!

**Comment by convenient** [comment]
Well, thats certainly one approach ! At least the module supports this flow.

A friend said that nginx may have had access to the header via `$sent_http_x_log_correlation_id`

> Header lines sent to a client have the prefix “sent_http_”, for example, $sent_http_content_range.
- http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format

And here's an example of adding a `sent_http` header in the access log for `sent_http_content_type`
```
log_format myCustomFormatTemplate '$remote_addr - $remote_user [$time_local]  '
    '"$request" $status $sent_http_content_type $body_bytes_sent '
    '"$http_referer" "$http_user_agent"';
```
- https://serverfault.com/a/451581/323168

So putting that together,  I expect you could add into original log format something like this
```
log_format examplelogformat '$time_local  $request $sent_http_x_log_correlation_id'
```

If you have the time to test that out, that would be useful to know so that I can update the README.md :)

**Comment by caduhigueras** [comment]
Sure

I will test it and let you know

Thanks!

**Comment by caduhigueras** [comment]
Hey @convenient 

This way you sent works perfectly!

Thanks again!

**Comment by convenient** [comment]
Amazing thanks @caduhigueras I'm not near a computer atm. If you fancy popping a PR into the README.md with instructions for nginx feel free :) but if you have more important stuff to be getting on with i'll try to remember to do it later 

thanks

**Comment by caduhigueras** [comment]
Hey @convenient 

It's done. 

Thanks again and great work on the module!
