### ISSUE TITLE
Feature request: add correlation ID as comment to sql queries

### ISSUE THREAD

**Issue by robolmos** [AmpersandHQ/magento2-log-correlation-id#25]
I think it would be useful to also have the correlation ID added as a comment to the database queries. That would make it easier to track down where slow queries in the mysql/mariadb process log are coming from.

One method is to use sqlcommenter spec: https://google.github.io/sqlcommenter/

I haven't found any other magento modules or lower-level php libraries that could do this for magento and this module seems like a good candidate for such functionality.

Later on it would be nice if the module provides a way to add additional fields to the query comment for things like OpenTelemetry values.

**Comment by convenient** [comment]
Hey @robolmos 

I have actually thought a few times that adding it to SQL queries would be very useful but never got around to investigating it.

Thanks for the link, we're coming up to holiday season so am quite busy with other work, PRs or POCs are welcome on this repository if you've implementation ideas, or it may be a while till we get to this.

**Comment by convenient** [comment]
Thoughts
- Might be neat to also push the `cid` into https://www.php.net/manual/en/function.cli-set-process-title.php to easily map the long running process to the queries in the database
- Might be able to do something with `\Magento\Framework\DB\Adapter\Pdo\Mysql::setQueryHook` to add as a comment

**Comment by convenient** [comment]
Hey @robolmos I've been doing some experimentation here https://github.com/AmpersandHQ/magento2-log-correlation-id/pull/27/files#diff-ef207817340fe13419474370bb908f4997081c130a4f8b4c4cdfb42b924817cfR66

I think starting with just adding the correlation ID will be enough, then reviewing to add opentelemetry more fully may follow.

Do you think you'll be able to have a review of the branch or check it out into a project to review or play around with?
